# Generated by Django 4.1.4 on 2022-12-24 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='point',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text="If user deleted than this field will change to True, but reopen account won't change anything. ", null=True, verbose_name='Deleted Account'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_point',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Total Point'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_spend_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Total Spend Amount'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='If user wants to delete account than change this field to True. If this seleted than all other objects related to this user will be marked as deleted too.If User try to reopen account than just make this false but it will not reverse other related objects. ', null=True, verbose_name='Deleted Account'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, help_text='Give a name to this address like Home or Office', max_length=150, null=True, unique=True, verbose_name='Address Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_point',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Current Point'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='None', max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Normal', max_length=50, null=True, verbose_name='Membership'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, default='photos/default-user-avatar.png', null=True, upload_to='photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point_used',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Point Used'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Legit', 'Legit'), ('Banned', 'Banned')], default='Legit', max_length=10, null=True, verbose_name='User Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', null=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
