version: "3.9"

services:
  pgadminMicro:
    image: truecharts/pgadmin4:6.17.0
    container_name: pgadminMicro
    restart: never
    environment:
      PGDATA: ${PGDATA}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - microtest
    depends_on:
      - accountDB
    volumes:
      - pgadminMicro:/var/lib/pgadmin


  account:
    build:
      context: ./Accounts
    command: sh -c "/project/run.sh"
    volumes:
      - type: bind
        source: ./Accounts
        target: /project
    depends_on:
      - accountDB
    ports:
      - "127.0.0.1:8000:8000"
    restart: never
    environment:
      DJ_ENVIRONMENT: ${DJ_ENVIRONMENT}
      DJ_KEY_AUTH: ${DJ_KEY_AUTH}
      DEBUG: ${DEBUG}
      DEFAULT_DB_NAME: ${ACCOUNT_DB}
      DEFAULT_DB_USER: ${ACCOUNT_USER}
      DEFAULT_DB_PASSWORD: ${ACCOUNT_PASSWORD}
      DEFAULT_DB_HOST: ${ACCOUNT_HOST}
      DEFAULT_DB_PORT: ${ACCOUNT_PORT}
    networks:
      - microtest


  accountDB:
    image: postgres:15.1-alpine3.17
    container_name: accountDB
    networks:
      - microtest
    restart: never
    environment:
      POSTGRES_DB: ${ACCOUNT_DB}
      POSTGRES_USER: ${ACCOUNT_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_PASSWORD}
      POSTGRES_HOST: ${ACCOUNT_HOST}
    volumes:
      - accountDB_data1:/data/postgres
      - accountDB_data2:/var/lib/postgresql/data


networks:
  microtest:
    driver: bridge

volumes:
  accountDB_data1:
  accountDB_data2:
  pgadminMicro: