from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from apps.common.models import BaseModel
from apps.token.rsa_key import generate_rsa

class RsaKey(BaseModel):
    public = models.BinaryField(verbose_name='Public Key', editable=False)
    private = models.BinaryField(verbose_name='Private Key', editable=False)
    active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f"rsa_key-{self.id}"

    def clean(self):
        if self._state.adding == True:
            if self.public or self.private:
                raise ValidationError(_("Can't set value in an autogenerated field"))
            if not self.active:
                raise ValidationError(_("Sorry you don't need to set value"))
            
            olds = RsaKey.objects.filter(active=True)
            [old.save() for old in olds]

        if self.id:
            self.active = False

    def save(self, *args, **kwargs):
        self.full_clean()
        if self._state.adding == True:
            self.private, self.public = generate_rsa()
        return super().save(*args, **kwargs)


class AuthToken(BaseModel):
    pass