# Generated by Django 4.1.6 on 2023-02-09 12:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('token', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.BinaryField(blank=True, null=True, unique=True, verbose_name='Access Token')),
                ('exp', models.DateTimeField(default=datetime.datetime(2023, 2, 10, 12, 32, 25, 623342, tzinfo=datetime.timezone.utc), editable=False)),
                ('is_valid', models.BooleanField(blank=True, default=False, null=True)),
                ('payload', models.JSONField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rsakey',
            name='private',
            field=models.BinaryField(unique=True, verbose_name='Private Key'),
        ),
        migrations.AlterField(
            model_name='rsakey',
            name='public',
            field=models.BinaryField(unique=True, verbose_name='Public Key'),
        ),
        migrations.AddConstraint(
            model_name='rsakey',
            constraint=models.UniqueConstraint(fields=('public', 'private'), name='unique_key_pair'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='authtoken',
            constraint=models.UniqueConstraint(fields=('user', 'access_token'), name='unique_auth_token'),
        ),
    ]
