# Generated by Django 4.1.6 on 2023-02-18 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token', '0002_authtoken_alter_rsakey_private_alter_rsakey_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='jti',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='exp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 19, 30, 48, 848664, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
