# Generated by Django 4.1.7 on 2023-02-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_deleted',
        ),
    ]
