# Generated by Django 4.1.7 on 2023-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New Account'), ('Banned', 'Banned Account')], default='New', max_length=10, null=True, verbose_name='User Status'),
        ),
    ]
