# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account/grpc/account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61\x63\x63ount/grpc/account.proto\x12\x10settings.account\x1a\x1bgoogle/protobuf/empty.proto\"$\n\x16QuestionDestroyRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x15\n\x13QuestionListRequest\"K\n\x14QuestionListResponse\x12\x33\n\x07results\x18\x01 \x03(\x0b\x32\".settings.account.QuestionResponse\"s\n\x1cQuestionPartialUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rquestion_text\x18\x02 \x01(\t\x12\x10\n\x08pub_date\x18\x03 \x01(\t\x12\x1e\n\x16_partial_update_fields\x18\x04 \x03(\t\"F\n\x0fQuestionRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rquestion_text\x18\x02 \x01(\t\x12\x10\n\x08pub_date\x18\x03 \x01(\t\"G\n\x10QuestionResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rquestion_text\x18\x02 \x01(\t\x12\x10\n\x08pub_date\x18\x03 \x01(\t\"%\n\x17QuestionRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xa6\x04\n\x12QuestionController\x12Q\n\x06\x43reate\x12!.settings.account.QuestionRequest\x1a\".settings.account.QuestionResponse\"\x00\x12M\n\x07\x44\x65stroy\x12(.settings.account.QuestionDestroyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12W\n\x04List\x12%.settings.account.QuestionListRequest\x1a&.settings.account.QuestionListResponse\"\x00\x12\x65\n\rPartialUpdate\x12..settings.account.QuestionPartialUpdateRequest\x1a\".settings.account.QuestionResponse\"\x00\x12[\n\x08Retrieve\x12).settings.account.QuestionRetrieveRequest\x1a\".settings.account.QuestionResponse\"\x00\x12Q\n\x06Update\x12!.settings.account.QuestionRequest\x1a\".settings.account.QuestionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account.grpc.account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUESTIONDESTROYREQUEST._serialized_start=77
  _QUESTIONDESTROYREQUEST._serialized_end=113
  _QUESTIONLISTREQUEST._serialized_start=115
  _QUESTIONLISTREQUEST._serialized_end=136
  _QUESTIONLISTRESPONSE._serialized_start=138
  _QUESTIONLISTRESPONSE._serialized_end=213
  _QUESTIONPARTIALUPDATEREQUEST._serialized_start=215
  _QUESTIONPARTIALUPDATEREQUEST._serialized_end=330
  _QUESTIONREQUEST._serialized_start=332
  _QUESTIONREQUEST._serialized_end=402
  _QUESTIONRESPONSE._serialized_start=404
  _QUESTIONRESPONSE._serialized_end=475
  _QUESTIONRETRIEVEREQUEST._serialized_start=477
  _QUESTIONRETRIEVEREQUEST._serialized_end=514
  _QUESTIONCONTROLLER._serialized_start=517
  _QUESTIONCONTROLLER._serialized_end=1067
# @@protoc_insertion_point(module_scope)
