# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from account.grpc import account_pb2 as account_dot_grpc_dot_account__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class QuestionControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/settings.account.QuestionController/Create',
                request_serializer=account_dot_grpc_dot_account__pb2.QuestionRequest.SerializeToString,
                response_deserializer=account_dot_grpc_dot_account__pb2.QuestionResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/settings.account.QuestionController/Destroy',
                request_serializer=account_dot_grpc_dot_account__pb2.QuestionDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/settings.account.QuestionController/List',
                request_serializer=account_dot_grpc_dot_account__pb2.QuestionListRequest.SerializeToString,
                response_deserializer=account_dot_grpc_dot_account__pb2.QuestionListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/settings.account.QuestionController/PartialUpdate',
                request_serializer=account_dot_grpc_dot_account__pb2.QuestionPartialUpdateRequest.SerializeToString,
                response_deserializer=account_dot_grpc_dot_account__pb2.QuestionResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/settings.account.QuestionController/Retrieve',
                request_serializer=account_dot_grpc_dot_account__pb2.QuestionRetrieveRequest.SerializeToString,
                response_deserializer=account_dot_grpc_dot_account__pb2.QuestionResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/settings.account.QuestionController/Update',
                request_serializer=account_dot_grpc_dot_account__pb2.QuestionRequest.SerializeToString,
                response_deserializer=account_dot_grpc_dot_account__pb2.QuestionResponse.FromString,
                )


class QuestionControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuestionControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=account_dot_grpc_dot_account__pb2.QuestionRequest.FromString,
                    response_serializer=account_dot_grpc_dot_account__pb2.QuestionResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=account_dot_grpc_dot_account__pb2.QuestionDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=account_dot_grpc_dot_account__pb2.QuestionListRequest.FromString,
                    response_serializer=account_dot_grpc_dot_account__pb2.QuestionListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=account_dot_grpc_dot_account__pb2.QuestionPartialUpdateRequest.FromString,
                    response_serializer=account_dot_grpc_dot_account__pb2.QuestionResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=account_dot_grpc_dot_account__pb2.QuestionRetrieveRequest.FromString,
                    response_serializer=account_dot_grpc_dot_account__pb2.QuestionResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=account_dot_grpc_dot_account__pb2.QuestionRequest.FromString,
                    response_serializer=account_dot_grpc_dot_account__pb2.QuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'settings.account.QuestionController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QuestionController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.account.QuestionController/Create',
            account_dot_grpc_dot_account__pb2.QuestionRequest.SerializeToString,
            account_dot_grpc_dot_account__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.account.QuestionController/Destroy',
            account_dot_grpc_dot_account__pb2.QuestionDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.account.QuestionController/List',
            account_dot_grpc_dot_account__pb2.QuestionListRequest.SerializeToString,
            account_dot_grpc_dot_account__pb2.QuestionListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.account.QuestionController/PartialUpdate',
            account_dot_grpc_dot_account__pb2.QuestionPartialUpdateRequest.SerializeToString,
            account_dot_grpc_dot_account__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.account.QuestionController/Retrieve',
            account_dot_grpc_dot_account__pb2.QuestionRetrieveRequest.SerializeToString,
            account_dot_grpc_dot_account__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.account.QuestionController/Update',
            account_dot_grpc_dot_account__pb2.QuestionRequest.SerializeToString,
            account_dot_grpc_dot_account__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
