# Generated by Django 4.1.4 on 2022-12-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_address_unique_address_profile_unique_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_point',
        ),
    ]
