# Generated by Django 4.1.4 on 2022-12-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_created_profile_updated_user_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otptoken',
            options={'verbose_name': 'OTPToken', 'verbose_name_plural': 'OTPtokens'},
        ),
        migrations.AddField(
            model_name='otptoken',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Designates whether this token should be treated as active. Unselect this to make it invalidate.', null=True, verbose_name='active'),
        ),
    ]
