# Generated by Django 4.1.4 on 2022-12-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_otptoken_options_otptoken_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='token',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
